version: '3.8'

services:
  # Frontend Next.js Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001/
    volumes:
      # Mount source code for development (comment out for production)
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - app-network

  # Backend API (placeholder - replace with your actual backend)
  backend:
    # Replace this with your actual backend image or build context
    image: node:18-alpine
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    # Add your backend configuration here
    command: ["sh", "-c", "echo 'Backend placeholder - replace with your actual backend service' && sleep infinity"]
    networks:
      - app-network

  # Database (example with PostgreSQL)
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=projecthub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge

